"""empty message

Revision ID: 6ab47f1168c8
Revises: 0b3b9528ac23
Create Date: 2017-01-03 15:35:14.020052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab47f1168c8'
down_revision = '0b3b9528ac23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
