"""empty message

Revision ID: 8f9d7bd53596
Revises: 
Create Date: 2016-12-05 15:33:51.113229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9d7bd53596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemonTeamBuilderTest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_dex', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('forme', sa.String(), nullable=True),
    sa.Column('type1', sa.String(), nullable=True),
    sa.Column('type2', sa.String(), nullable=True),
    sa.Column('ability1', sa.String(), nullable=True),
    sa.Column('ability2', sa.String(), nullable=True),
    sa.Column('abilityH', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('spattack', sa.Integer(), nullable=True),
    sa.Column('spdefense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('dex1', sa.String(), nullable=True),
    sa.Column('dex2', sa.String(), nullable=True),
    sa.Column('pkmn_class', sa.String(), nullable=True),
    sa.Column('percent_male', sa.Float(), nullable=True),
    sa.Column('percent_female', sa.Float(), nullable=True),
    sa.Column('pre_evolution', sa.String(), nullable=True),
    sa.Column('egg_group1', sa.String(), nullable=True),
    sa.Column('egg_group2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemonTeamBuilderTest')
    # ### end Alembic commands ###
